// <auto-generated />
using System;
using DbConfigurator.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DbConfigurator.DataAccess.Migrations
{
    [DbContext(typeof(DbConfiguratorDbContext))]
    partial class DbConfiguratorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DbConfigurator.Model.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Area");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Americas"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Central Europe"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Growing Markets"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Northern Europe"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Southern Europe"
                        },
                        new
                        {
                            Id = 99,
                            Name = "ANY"
                        });
                });

            modelBuilder.Entity("DbConfigurator.Model.AreaBuisnessUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<int>("BuisnessUnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("BuisnessUnitId");

                    b.ToTable("AreaBuisnessUnit");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AreaId = 1,
                            BuisnessUnitId = 1
                        },
                        new
                        {
                            Id = 2,
                            AreaId = 1,
                            BuisnessUnitId = 2
                        },
                        new
                        {
                            Id = 3,
                            AreaId = 2,
                            BuisnessUnitId = 3
                        },
                        new
                        {
                            Id = 4,
                            AreaId = 2,
                            BuisnessUnitId = 4
                        },
                        new
                        {
                            Id = 5,
                            AreaId = 3,
                            BuisnessUnitId = 5
                        },
                        new
                        {
                            Id = 6,
                            AreaId = 3,
                            BuisnessUnitId = 6
                        },
                        new
                        {
                            Id = 7,
                            AreaId = 3,
                            BuisnessUnitId = 7
                        },
                        new
                        {
                            Id = 8,
                            AreaId = 4,
                            BuisnessUnitId = 8
                        },
                        new
                        {
                            Id = 9,
                            AreaId = 4,
                            BuisnessUnitId = 9
                        },
                        new
                        {
                            Id = 10,
                            AreaId = 4,
                            BuisnessUnitId = 10
                        },
                        new
                        {
                            Id = 11,
                            AreaId = 5,
                            BuisnessUnitId = 11
                        },
                        new
                        {
                            Id = 12,
                            AreaId = 5,
                            BuisnessUnitId = 12
                        },
                        new
                        {
                            Id = 13,
                            AreaId = 5,
                            BuisnessUnitId = 13
                        },
                        new
                        {
                            Id = 14,
                            AreaId = 1,
                            BuisnessUnitId = 99
                        },
                        new
                        {
                            Id = 15,
                            AreaId = 2,
                            BuisnessUnitId = 99
                        },
                        new
                        {
                            Id = 16,
                            AreaId = 3,
                            BuisnessUnitId = 99
                        },
                        new
                        {
                            Id = 17,
                            AreaId = 4,
                            BuisnessUnitId = 99
                        },
                        new
                        {
                            Id = 18,
                            AreaId = 5,
                            BuisnessUnitId = 99
                        },
                        new
                        {
                            Id = 19,
                            AreaId = 99,
                            BuisnessUnitId = 99
                        });
                });

            modelBuilder.Entity("DbConfigurator.Model.BuisnessUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("BuisnessUnit");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "NAO"
                        },
                        new
                        {
                            Id = 2,
                            Name = "SAM"
                        },
                        new
                        {
                            Id = 3,
                            Name = "GER"
                        },
                        new
                        {
                            Id = 4,
                            Name = "CEE"
                        },
                        new
                        {
                            Id = 5,
                            Name = "MEK"
                        },
                        new
                        {
                            Id = 6,
                            Name = "AFR"
                        },
                        new
                        {
                            Id = 7,
                            Name = "IND"
                        },
                        new
                        {
                            Id = 8,
                            Name = "APAC"
                        },
                        new
                        {
                            Id = 9,
                            Name = "BTN"
                        },
                        new
                        {
                            Id = 10,
                            Name = "UK&I"
                        },
                        new
                        {
                            Id = 11,
                            Name = "ITA"
                        },
                        new
                        {
                            Id = 12,
                            Name = "IBE"
                        },
                        new
                        {
                            Id = 13,
                            Name = "FRA"
                        },
                        new
                        {
                            Id = 99,
                            Name = "ANY"
                        });
                });

            modelBuilder.Entity("DbConfigurator.Model.BuisnessUnitCountry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuisnessUnitId")
                        .HasColumnType("int");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuisnessUnitId");

                    b.HasIndex("CountryId");

                    b.ToTable("BuisnessUnitCountry");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuisnessUnitId = 1,
                            CountryId = 1
                        },
                        new
                        {
                            Id = 2,
                            BuisnessUnitId = 1,
                            CountryId = 2
                        },
                        new
                        {
                            Id = 3,
                            BuisnessUnitId = 1,
                            CountryId = 3
                        },
                        new
                        {
                            Id = 4,
                            BuisnessUnitId = 1,
                            CountryId = 4
                        },
                        new
                        {
                            Id = 5,
                            BuisnessUnitId = 1,
                            CountryId = 5
                        },
                        new
                        {
                            Id = 6,
                            BuisnessUnitId = 2,
                            CountryId = 6
                        },
                        new
                        {
                            Id = 7,
                            BuisnessUnitId = 2,
                            CountryId = 7
                        },
                        new
                        {
                            Id = 8,
                            BuisnessUnitId = 2,
                            CountryId = 8
                        },
                        new
                        {
                            Id = 9,
                            BuisnessUnitId = 2,
                            CountryId = 9
                        },
                        new
                        {
                            Id = 10,
                            BuisnessUnitId = 2,
                            CountryId = 10
                        },
                        new
                        {
                            Id = 11,
                            BuisnessUnitId = 2,
                            CountryId = 11
                        },
                        new
                        {
                            Id = 12,
                            BuisnessUnitId = 2,
                            CountryId = 12
                        },
                        new
                        {
                            Id = 13,
                            BuisnessUnitId = 3,
                            CountryId = 13
                        },
                        new
                        {
                            Id = 14,
                            BuisnessUnitId = 4,
                            CountryId = 14
                        },
                        new
                        {
                            Id = 15,
                            BuisnessUnitId = 4,
                            CountryId = 15
                        },
                        new
                        {
                            Id = 16,
                            BuisnessUnitId = 4,
                            CountryId = 16
                        },
                        new
                        {
                            Id = 17,
                            BuisnessUnitId = 4,
                            CountryId = 17
                        },
                        new
                        {
                            Id = 18,
                            BuisnessUnitId = 4,
                            CountryId = 18
                        },
                        new
                        {
                            Id = 19,
                            BuisnessUnitId = 4,
                            CountryId = 19
                        },
                        new
                        {
                            Id = 20,
                            BuisnessUnitId = 4,
                            CountryId = 20
                        },
                        new
                        {
                            Id = 21,
                            BuisnessUnitId = 4,
                            CountryId = 21
                        },
                        new
                        {
                            Id = 22,
                            BuisnessUnitId = 4,
                            CountryId = 22
                        },
                        new
                        {
                            Id = 23,
                            BuisnessUnitId = 4,
                            CountryId = 23
                        },
                        new
                        {
                            Id = 24,
                            BuisnessUnitId = 4,
                            CountryId = 24
                        },
                        new
                        {
                            Id = 25,
                            BuisnessUnitId = 4,
                            CountryId = 25
                        },
                        new
                        {
                            Id = 26,
                            BuisnessUnitId = 4,
                            CountryId = 26
                        },
                        new
                        {
                            Id = 27,
                            BuisnessUnitId = 4,
                            CountryId = 27
                        },
                        new
                        {
                            Id = 28,
                            BuisnessUnitId = 4,
                            CountryId = 28
                        },
                        new
                        {
                            Id = 29,
                            BuisnessUnitId = 4,
                            CountryId = 29
                        },
                        new
                        {
                            Id = 30,
                            BuisnessUnitId = 5,
                            CountryId = 30
                        },
                        new
                        {
                            Id = 31,
                            BuisnessUnitId = 5,
                            CountryId = 31
                        },
                        new
                        {
                            Id = 32,
                            BuisnessUnitId = 5,
                            CountryId = 32
                        },
                        new
                        {
                            Id = 33,
                            BuisnessUnitId = 5,
                            CountryId = 33
                        },
                        new
                        {
                            Id = 34,
                            BuisnessUnitId = 5,
                            CountryId = 34
                        },
                        new
                        {
                            Id = 35,
                            BuisnessUnitId = 5,
                            CountryId = 35
                        },
                        new
                        {
                            Id = 36,
                            BuisnessUnitId = 5,
                            CountryId = 36
                        },
                        new
                        {
                            Id = 37,
                            BuisnessUnitId = 6,
                            CountryId = 37
                        },
                        new
                        {
                            Id = 38,
                            BuisnessUnitId = 6,
                            CountryId = 38
                        },
                        new
                        {
                            Id = 39,
                            BuisnessUnitId = 6,
                            CountryId = 39
                        },
                        new
                        {
                            Id = 40,
                            BuisnessUnitId = 6,
                            CountryId = 40
                        },
                        new
                        {
                            Id = 41,
                            BuisnessUnitId = 6,
                            CountryId = 41
                        },
                        new
                        {
                            Id = 42,
                            BuisnessUnitId = 6,
                            CountryId = 42
                        },
                        new
                        {
                            Id = 43,
                            BuisnessUnitId = 6,
                            CountryId = 43
                        },
                        new
                        {
                            Id = 44,
                            BuisnessUnitId = 6,
                            CountryId = 44
                        },
                        new
                        {
                            Id = 45,
                            BuisnessUnitId = 6,
                            CountryId = 45
                        },
                        new
                        {
                            Id = 46,
                            BuisnessUnitId = 6,
                            CountryId = 46
                        },
                        new
                        {
                            Id = 47,
                            BuisnessUnitId = 6,
                            CountryId = 47
                        },
                        new
                        {
                            Id = 48,
                            BuisnessUnitId = 6,
                            CountryId = 48
                        },
                        new
                        {
                            Id = 49,
                            BuisnessUnitId = 6,
                            CountryId = 49
                        },
                        new
                        {
                            Id = 50,
                            BuisnessUnitId = 7,
                            CountryId = 50
                        },
                        new
                        {
                            Id = 51,
                            BuisnessUnitId = 8,
                            CountryId = 51
                        },
                        new
                        {
                            Id = 52,
                            BuisnessUnitId = 8,
                            CountryId = 52
                        },
                        new
                        {
                            Id = 53,
                            BuisnessUnitId = 8,
                            CountryId = 53
                        },
                        new
                        {
                            Id = 54,
                            BuisnessUnitId = 8,
                            CountryId = 54
                        },
                        new
                        {
                            Id = 55,
                            BuisnessUnitId = 8,
                            CountryId = 55
                        },
                        new
                        {
                            Id = 56,
                            BuisnessUnitId = 8,
                            CountryId = 56
                        },
                        new
                        {
                            Id = 57,
                            BuisnessUnitId = 8,
                            CountryId = 57
                        },
                        new
                        {
                            Id = 58,
                            BuisnessUnitId = 8,
                            CountryId = 58
                        },
                        new
                        {
                            Id = 59,
                            BuisnessUnitId = 8,
                            CountryId = 59
                        },
                        new
                        {
                            Id = 60,
                            BuisnessUnitId = 8,
                            CountryId = 60
                        },
                        new
                        {
                            Id = 61,
                            BuisnessUnitId = 8,
                            CountryId = 61
                        },
                        new
                        {
                            Id = 62,
                            BuisnessUnitId = 8,
                            CountryId = 62
                        },
                        new
                        {
                            Id = 63,
                            BuisnessUnitId = 9,
                            CountryId = 63
                        },
                        new
                        {
                            Id = 64,
                            BuisnessUnitId = 9,
                            CountryId = 64
                        },
                        new
                        {
                            Id = 65,
                            BuisnessUnitId = 9,
                            CountryId = 65
                        },
                        new
                        {
                            Id = 66,
                            BuisnessUnitId = 9,
                            CountryId = 66
                        },
                        new
                        {
                            Id = 67,
                            BuisnessUnitId = 9,
                            CountryId = 67
                        },
                        new
                        {
                            Id = 68,
                            BuisnessUnitId = 9,
                            CountryId = 68
                        },
                        new
                        {
                            Id = 69,
                            BuisnessUnitId = 9,
                            CountryId = 69
                        },
                        new
                        {
                            Id = 70,
                            BuisnessUnitId = 9,
                            CountryId = 70
                        },
                        new
                        {
                            Id = 71,
                            BuisnessUnitId = 9,
                            CountryId = 71
                        },
                        new
                        {
                            Id = 72,
                            BuisnessUnitId = 10,
                            CountryId = 72
                        },
                        new
                        {
                            Id = 73,
                            BuisnessUnitId = 10,
                            CountryId = 73
                        },
                        new
                        {
                            Id = 74,
                            BuisnessUnitId = 11,
                            CountryId = 74
                        },
                        new
                        {
                            Id = 75,
                            BuisnessUnitId = 12,
                            CountryId = 75
                        },
                        new
                        {
                            Id = 76,
                            BuisnessUnitId = 12,
                            CountryId = 76
                        },
                        new
                        {
                            Id = 77,
                            BuisnessUnitId = 12,
                            CountryId = 77
                        },
                        new
                        {
                            Id = 78,
                            BuisnessUnitId = 13,
                            CountryId = 78
                        },
                        new
                        {
                            Id = 79,
                            BuisnessUnitId = 13,
                            CountryId = 79
                        },
                        new
                        {
                            Id = 80,
                            BuisnessUnitId = 13,
                            CountryId = 80
                        },
                        new
                        {
                            Id = 81,
                            BuisnessUnitId = 13,
                            CountryId = 81
                        },
                        new
                        {
                            Id = 82,
                            BuisnessUnitId = 1,
                            CountryId = 99
                        },
                        new
                        {
                            Id = 83,
                            BuisnessUnitId = 2,
                            CountryId = 99
                        },
                        new
                        {
                            Id = 84,
                            BuisnessUnitId = 3,
                            CountryId = 99
                        },
                        new
                        {
                            Id = 85,
                            BuisnessUnitId = 4,
                            CountryId = 99
                        },
                        new
                        {
                            Id = 86,
                            BuisnessUnitId = 5,
                            CountryId = 99
                        },
                        new
                        {
                            Id = 87,
                            BuisnessUnitId = 6,
                            CountryId = 99
                        },
                        new
                        {
                            Id = 88,
                            BuisnessUnitId = 7,
                            CountryId = 99
                        },
                        new
                        {
                            Id = 89,
                            BuisnessUnitId = 8,
                            CountryId = 99
                        },
                        new
                        {
                            Id = 90,
                            BuisnessUnitId = 9,
                            CountryId = 99
                        },
                        new
                        {
                            Id = 91,
                            BuisnessUnitId = 10,
                            CountryId = 99
                        },
                        new
                        {
                            Id = 92,
                            BuisnessUnitId = 11,
                            CountryId = 99
                        },
                        new
                        {
                            Id = 93,
                            BuisnessUnitId = 12,
                            CountryId = 99
                        },
                        new
                        {
                            Id = 94,
                            BuisnessUnitId = 13,
                            CountryId = 99
                        },
                        new
                        {
                            Id = 95,
                            BuisnessUnitId = 99,
                            CountryId = 99
                        });
                });

            modelBuilder.Entity("DbConfigurator.Model.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("Id");

                    b.ToTable("Country");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Canada",
                            ShortCode = "CA"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Guatemala",
                            ShortCode = "GT"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mexico",
                            ShortCode = "MX"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Puerto Rico",
                            ShortCode = "PR"
                        },
                        new
                        {
                            Id = 5,
                            Name = "USA",
                            ShortCode = "US"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Argentina",
                            ShortCode = "AR"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Brazil",
                            ShortCode = "BR"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Chile",
                            ShortCode = "CL"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Colombia",
                            ShortCode = "CO"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Peru",
                            ShortCode = "PE"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Uruguay",
                            ShortCode = "UY"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Venezuela",
                            ShortCode = "VE"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Germany",
                            ShortCode = "DE"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Poland",
                            ShortCode = "PL"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Russian Federation",
                            ShortCode = "RU"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Austria",
                            ShortCode = "AT"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Bulgaria",
                            ShortCode = "BG"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Switzerland",
                            ShortCode = "CH"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Cyprus",
                            ShortCode = "CY"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Czech Republic",
                            ShortCode = "CZ"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Greece",
                            ShortCode = "GR"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Croatia",
                            ShortCode = "HR"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Hungary",
                            ShortCode = "HU"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Israel",
                            ShortCode = "IL"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Kasakhstan",
                            ShortCode = "KZ"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Romania",
                            ShortCode = "RO"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Serbia",
                            ShortCode = "RS"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Slovakia",
                            ShortCode = "SK"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Ukraine",
                            ShortCode = "UA"
                        },
                        new
                        {
                            Id = 30,
                            Name = "United Arab Emirates",
                            ShortCode = "AE"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Egypt",
                            ShortCode = "EG"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Iran",
                            ShortCode = "IR"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Lebanon",
                            ShortCode = "LB"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Qatar",
                            ShortCode = "QA"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Saudi Arabia",
                            ShortCode = "SA"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Turkey",
                            ShortCode = "TR"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Burkina Faso",
                            ShortCode = "BF"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Benin",
                            ShortCode = "BJ"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Cote d'Ivoire",
                            ShortCode = "CI"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Algeria",
                            ShortCode = "DZ"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Gabon",
                            ShortCode = "GA"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Ivory Coast",
                            ShortCode = "CI"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Morocco",
                            ShortCode = "MA"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Madagascar",
                            ShortCode = "MG"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Mali",
                            ShortCode = "ML"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Mauritius",
                            ShortCode = "MU"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Senegal",
                            ShortCode = "SN"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Tunisia",
                            ShortCode = "TN"
                        },
                        new
                        {
                            Id = 49,
                            Name = "South Africa",
                            ShortCode = "ZA"
                        },
                        new
                        {
                            Id = 50,
                            Name = "India",
                            ShortCode = "IN"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Australia",
                            ShortCode = "AU"
                        },
                        new
                        {
                            Id = 52,
                            Name = "People Rep China",
                            ShortCode = "CN"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Hong Kong",
                            ShortCode = "HK"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Indonesia",
                            ShortCode = "ID"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Japan",
                            ShortCode = "JP"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Korea",
                            ShortCode = "KR"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Malaysia",
                            ShortCode = "MY"
                        },
                        new
                        {
                            Id = 58,
                            Name = "New Zealand",
                            ShortCode = "NZ"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Philippines",
                            ShortCode = "PH"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Singapore",
                            ShortCode = "SG"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Thailand",
                            ShortCode = "TH"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Taiwan",
                            ShortCode = "TW"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Belgium",
                            ShortCode = "BE"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Denmark",
                            ShortCode = "DK"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Estonia",
                            ShortCode = "EE"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Finland",
                            ShortCode = "FI"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Lithuania",
                            ShortCode = "LT"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Luxembourg",
                            ShortCode = "LU"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Netherlands",
                            ShortCode = "NL"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Norway",
                            ShortCode = "NO"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Sweden",
                            ShortCode = "SE"
                        },
                        new
                        {
                            Id = 72,
                            Name = "United Kingdom",
                            ShortCode = "GB"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Ireland",
                            ShortCode = "IE"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Italy",
                            ShortCode = "IT"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Andorra",
                            ShortCode = "AD"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Spain",
                            ShortCode = "ES"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Portugal",
                            ShortCode = "PT"
                        },
                        new
                        {
                            Id = 78,
                            Name = "France",
                            ShortCode = "FR"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Morocco",
                            ShortCode = "MA"
                        },
                        new
                        {
                            Id = 80,
                            Name = "New Caledonia",
                            ShortCode = "NC"
                        },
                        new
                        {
                            Id = 81,
                            Name = "French Polynesia",
                            ShortCode = "PF"
                        },
                        new
                        {
                            Id = 99,
                            Name = "ANY",
                            ShortCode = "ANY"
                        });
                });

            modelBuilder.Entity("DbConfigurator.Model.DistributionInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<int>("BuisnessUnitId")
                        .HasColumnType("int");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<int>("PriorityId")
                        .HasColumnType("int");

                    b.Property<int?>("RecipientsGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("BuisnessUnitId");

                    b.HasIndex("CountryId");

                    b.HasIndex("PriorityId");

                    b.HasIndex("RecipientsGroupId")
                        .IsUnique()
                        .HasFilter("[RecipientsGroupId] IS NOT NULL");

                    b.ToTable("DistributionInformation");
                });

            modelBuilder.Entity("DbConfigurator.Model.Priority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.HasKey("Id");

                    b.ToTable("Priority");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "P1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "P2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "P3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "P4"
                        },
                        new
                        {
                            Id = 99,
                            Name = "ANY"
                        });
                });

            modelBuilder.Entity("DbConfigurator.Model.Recipient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recipient");
                });

            modelBuilder.Entity("DbConfigurator.Model.RecipientsGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DistributionInformationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RecipientsGroup");
                });

            modelBuilder.Entity("RecipientRecipientsGroup", b =>
                {
                    b.Property<int>("RecipientsGroupsToId")
                        .HasColumnType("int");

                    b.Property<int>("RecipientsToId")
                        .HasColumnType("int");

                    b.HasKey("RecipientsGroupsToId", "RecipientsToId");

                    b.HasIndex("RecipientsToId");

                    b.ToTable("RecipientsGroupTo", (string)null);
                });

            modelBuilder.Entity("RecipientRecipientsGroup1", b =>
                {
                    b.Property<int>("RecipientsCcId")
                        .HasColumnType("int");

                    b.Property<int>("RecipientsGroupsCcId")
                        .HasColumnType("int");

                    b.HasKey("RecipientsCcId", "RecipientsGroupsCcId");

                    b.HasIndex("RecipientsGroupsCcId");

                    b.ToTable("RecipientsGroupCc", (string)null);
                });

            modelBuilder.Entity("DbConfigurator.Model.AreaBuisnessUnit", b =>
                {
                    b.HasOne("DbConfigurator.Model.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbConfigurator.Model.BuisnessUnit", "BuisnessUnit")
                        .WithMany()
                        .HasForeignKey("BuisnessUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("BuisnessUnit");
                });

            modelBuilder.Entity("DbConfigurator.Model.BuisnessUnitCountry", b =>
                {
                    b.HasOne("DbConfigurator.Model.BuisnessUnit", "BuisnessUnit")
                        .WithMany()
                        .HasForeignKey("BuisnessUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbConfigurator.Model.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuisnessUnit");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("DbConfigurator.Model.DistributionInformation", b =>
                {
                    b.HasOne("DbConfigurator.Model.Area", "Area")
                        .WithMany("DistributionInformations")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbConfigurator.Model.BuisnessUnit", "BuisnessUnit")
                        .WithMany("DistributionInformations")
                        .HasForeignKey("BuisnessUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbConfigurator.Model.Country", "Country")
                        .WithMany("DistributionInformations")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbConfigurator.Model.Priority", "Priority")
                        .WithMany("DistributionInformations")
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbConfigurator.Model.RecipientsGroup", "RecipientsGroup")
                        .WithOne("DistributionInformation")
                        .HasForeignKey("DbConfigurator.Model.DistributionInformation", "RecipientsGroupId");

                    b.Navigation("Area");

                    b.Navigation("BuisnessUnit");

                    b.Navigation("Country");

                    b.Navigation("Priority");

                    b.Navigation("RecipientsGroup");
                });

            modelBuilder.Entity("RecipientRecipientsGroup", b =>
                {
                    b.HasOne("DbConfigurator.Model.RecipientsGroup", null)
                        .WithMany()
                        .HasForeignKey("RecipientsGroupsToId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbConfigurator.Model.Recipient", null)
                        .WithMany()
                        .HasForeignKey("RecipientsToId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RecipientRecipientsGroup1", b =>
                {
                    b.HasOne("DbConfigurator.Model.Recipient", null)
                        .WithMany()
                        .HasForeignKey("RecipientsCcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbConfigurator.Model.RecipientsGroup", null)
                        .WithMany()
                        .HasForeignKey("RecipientsGroupsCcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DbConfigurator.Model.Area", b =>
                {
                    b.Navigation("DistributionInformations");
                });

            modelBuilder.Entity("DbConfigurator.Model.BuisnessUnit", b =>
                {
                    b.Navigation("DistributionInformations");
                });

            modelBuilder.Entity("DbConfigurator.Model.Country", b =>
                {
                    b.Navigation("DistributionInformations");
                });

            modelBuilder.Entity("DbConfigurator.Model.Priority", b =>
                {
                    b.Navigation("DistributionInformations");
                });

            modelBuilder.Entity("DbConfigurator.Model.RecipientsGroup", b =>
                {
                    b.Navigation("DistributionInformation")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
